### PR TITLE
support gdeh042Z98

### PR DESCRIPTION
**Pull request by meibao-real**
support gdeh042Z98 display

### CODE REVIEW

**Review by martinberlin — APPROVED** [review]
Looks great!
Thanks for your contribution @meibao-real

**Comment by martinberlin** [comment]
@meibao-real it would be possible that you upload here a picture of the epaper ?

(With your phone does not need to be a great picture)
So I will add it in the [WiKi](https://github.com/martinberlin/cale-idf/wiki)

**Comment by meibao-real** [comment]
OK
gdeh042Z98

**Comment by martinberlin** [comment]
Nice action!
Thanks a lot. Is merged. Thanks for using CalEPD and for taking your time to understand it.
Now that you know how it works you could add any future epaper that has no class.

**Comment by meibao-real** [comment]
yeah, also, CalEPD is a great project

**Pull request merged**
